### ISSUE TITLE
Qase Newman Reporter does not return created Test Run ID

### ISSUE THREAD

**Issue by AmmarArnt** [qase-tms/qase-javascript#148]
I am running the Qase Newman Reporter as part of my CD pipeline. This reporter creates a test run in Qase, however it leaves it as an open (active) test run. I then have to go and manually complete it in the Qase UI.

I would like to programatically call the Qase API to complete this test run, however the system does not know the ID of the test run that was created by running the newman qase reporter.

Ideally an ID of the created test run should be returned on `newman run -r qase`, so that I can do whatever I want to in the remainder of the automated pipeline.

**Comment by 1ivliev** [comment]
Hello! We have a task in the backlog to improve newman-reporter-qase. At the moment, we are collecting user feedback. Could you create a feature request on our roadmap?
https://roadmap.qase.io

**Comment by AmmarArnt** [comment]
Ended up creating the test execution via Qase API, executing newman with the qase reporter, and then marking the test run as completed via Qase API:

```yaml
test:
    name: Run API tests
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Newman with Qase Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-qase
      - name: Download Postman Environment 
        run: |
          curl -H "X-API-Key: ${{ secrets.POSTMAN_API_KEY }}" https://api.getpostman.com/environments/${{ env.POSTMAN_ENVIRONMENT }} > environment.json
      - name: Start Test Run on Qase
        run: |
          curl -H "Token: ${{ secrets.QASE_TOKEN }}" -H "Accept: application/json" -H "Content-Type: application/json" --data "{ \"title\": \"DEV CD\", \"description\": \"Run on canary deployment ${{ steps.prep.outputs.CANARY_BUILD_ID }}. Triggered from: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\", \"is_autotest\": true, \"include_all_cases\": true }" -X POST https://api.qase.io/v1/run/${{env.QASE_PROJECT_B2C}} > qase-result.json
      - name: Get Test Run Id
        id: get-run-id
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'qase-result.json'
          prop_path: 'result.id'

      - name: Run Postman tests
        run: |
          newman run postman-collections/workflows.json --environment=environment.json -r qase --reporter-qase-logging --reporter-qase-projectCode ${{ env.QASE_PROJECT_NAME }} --reporter-qase-apiToken ${{ secrets.QASE_TOKEN }} --reporter-qase-runName "DEV CD" --reporter-qase-runDescription "Running on canary deployment ${{ steps.prep.outputs.CANARY_BUILD_ID }}" --reporter-qase-runId ${{steps.get-run-id.outputs.prop}} -x
          
      - name: Complete Test Run on Qase
        run: |
          curl -H "Token: ${{ secrets.QASE_TOKEN }}" -H "Accept: application/json" -X POST https://api.qase.io/v1/run/${{env.QASE_PROJECT_B2C}}/${{steps.get-run-id.outputs.prop}}/complete
```

Nevertheless, I'll open up a feature request to have this thing working more implicit.
