### ISSUE TITLE
Integration from Qase.io local=OK, but through GitLabCi doesn't work

### ISSUE THREAD

**Issue by cassiodamacena** [qase-tms/qase-javascript#334]
Integration of Qase.io with Cypres using (reporter: "cypress-qase-reporter") is integrating when running the tests locally, however, when running on the GitLab CI, it is not performing the integration.

I did not perform any additional configuration, since the "apiToken" is already included in the Project.

I'm using the following settings:
"reporter": "cypress-qase-reporter",
   "reporterOptions": {
     "apiToken": "my Token Here",
     "projectCode": "PROJECTCODE",
     "logging": true
  }

**Comment by pbielenda** [comment]
Could you provide some additional information? 

- How do you start your tests locally and how .gitlab-ci file looks like? 
- What happening when you running tests on gitlab? Do you have any helpful logs?

**Comment by cassiodamacena** [comment]
**Locally start the test with the command:**
`npx cypress run
`


In gitlab I'm running with the yaml below:
```
image: cypress/base:16

before_script:
     - npm install

test:
     script:
         #- $(npm bin)/cypress run
         - npm test
    
     artifacts:
         when: always
         paths:
             - cypress/videos/**/*.mp4
             - cypress/screenshots/**/*.png
         expire_in: 1 day
```

I'm using the following settings in cypress.json:
```
"reporter": "cypress-qase-reporter",
   "reporterOptions": {
     "apiToken": "my_token_here",
     "projectCode": "my_code_here",
     "logging": true
   },
```


GitlaCI is logging the following output on failure:
```
Uploading artifacts for failed job
00:02
Uploading artifacts...
cypress/videos/**/*.mp4: found 1 matching files and directories
cypress/screenshots/**/*.png: found 1 matching files and directories
Uploading artifacts as "archive" to coordinator... 201 Created id=14539 responseStatus=201 Created token=JP7iWhCs
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1

```


And the following output on success:
```
Uploading artifacts for successful job
00:02
Uploading artifacts...
cypress/videos/**/*.mp4: found 1 matching files and directories
WARNING: cypress/screenshots/**/*.png: no matching files. Ensure that the artifact path is relative to the working directory
Uploading artifacts as "archive" to coordinator... 201 Created id=14545 responseStatus=201 Created token=o9HVeY5u
Cleaning up project directory and file based variables
00:01
Job succeeded
```
